### ISSUE TITLE
Fix export.in issue preventing Ninja builds from completing

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#835]
The error looks like this:

```
[329/333] Generating ../export_albany.in
FAILED: export_albany.in
cd /nightlyCDash/build/IKTAlbany/dummy && /nightlyCDash/repos/Albany/cmake/CreateExportAlbany --bin-dir /nightlyCDash/build/IKTAlbany --install-lib-dir /nightlyCDash/build/IKTAlbanyInstall/lib64
Traceback (most recent call last):
  File "/nightlyCDash/repos/Albany/cmake/CreateExportAlbany", line 91, in <module>
    _main_func(__doc__)
  File "/nightlyCDash/repos/Albany/cmake/CreateExportAlbany", line 29, in _main_func
    with infile.open('r') as fd:
  File "/usr/lib64/python3.6/pathlib.py", line 1183, in open
    opener=self._opener)
  File "/usr/lib64/python3.6/pathlib.py", line 1037, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib64/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/nightlyCDash/build/IKTAlbany/dummy/CMakeFiles/dummy.dir/link.txt'
[330/333] Linking CXX executable dummy/dummy
[331/333] Linking CXX executable src/Albany
[332/333] Linking CXX executable src/AlbanyAnalysis
ninja: build stopped: cannot make progress due to previous errors.
Command exited with the value: 1
MakeCommand:/usr/bin/cmake --build . --config "Release" --target "install" -- -k 999999
Error(s) when building project
```

**Comment by ikalash** [comment]
@bartgol : when do you think you will fix this?  I do not want the CEE nightlies down for a prolonged period of time, as things could slip through the cracks in the testing.

**Comment by bartgol** [comment]
I do not have a timeline yet. Maybe sometimes this week?

**Comment by ikalash** [comment]
It looks like you fixed this @bartgol  - can you please confirm?  If so, I'll reenable the ninja builds.

**Comment by bartgol** [comment]
Well, it works on my machine. We can try to merge, and see what the nightlies do...
