### ISSUE TITLE
Issue with generating export_albany.in in Ninja builds

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#924]
Some of the builds on camobap are failing with the following error: 

```
[281/284] Generating ../export_albany.in
FAILED: export_albany.in
cd /nightlyCDash/build/IKTAlbanyFPECheckDbg && /nightlyCDash/repos/Albany/cmake/CreateExportAlbany --bin-dir /nightlyCDash/build/IKTAlbanyFPECheckDbg --install-lib-dir /usr/local/lib64 --cmake-generator Ninja
ERROR! Unexpected format of LINK_LIBRARIES line in build.ninja
Traceback (most recent call last):
  File "/nightlyCDash/repos/Albany/cmake/CreateExportAlbany", line 202, in <module>
    _main_func(__doc__)
  File "/nightlyCDash/repos/Albany/cmake/CreateExportAlbany", line 195, in _main_func
    run (bin_dir,install_lib_dir,generator)
  File "/nightlyCDash/repos/Albany/cmake/CreateExportAlbany", line 114, in run
    items = get_link_line_ninja (bin_dir)
  File "/nightlyCDash/repos/Albany/cmake/CreateExportAlbany", line 40, in get_link_line_ninja
    raise RuntimeError
RuntimeError
[282/284] Linking CXX executable dummy/dummy
[283/284] Linking CXX executable src/Albany
[284/284] Linking CXX executable src/AlbanyAnalysis
ninja: build stopped: cannot make progress due to previous errors.
Command exited with the value: 1
MakeCommand:/usr/bin/cmake --build . --config "Debug" --target "all" -- -
```

@bartgol could you please have a look?  I think we had a similar problem in the past due to things not playing well with ninja.

**Comment by ikalash** [comment]
@bartgol : can you please get this fixed this week?  I'd like the testing to be working again.

**Comment by bartgol** [comment]
Yeah, I'll get it done this week.

Btw, this is not the first time that something like this happened, as you mentioned. It might just be my lazy side talking, but...do we need to support a ninja build? Is it used in practice (not counting nightlies)?

**Comment by ikalash** [comment]
Ninja substantially speeds up build time so I would think our users would like it to be supported...

**Comment by mperego** [comment]
It seems we usually have issues with the albany export, which is a fairly new piece of CMake code. 
Given that the Albany export is only needed for MALI, if this keeps happening we can disable it by dfault and enable it only when MALI interface is enabled.

**Comment by ikalash** [comment]
I like what @mperego is proposing.  This would be a good solution - just to disable the creation of the file if not building MALI.

**Comment by bartgol** [comment]
That's reasonable. I can do that real quick.
