### ISSUE TITLE
Failing PyAlbany tests

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#990]
It looks like we also have some failing PyAlbany tests after the fixes to the builds / configures last week.  In the dashboard, PyAlbany_RSVDsinglePass is failing: 

https://sems-cdash-son.sandia.gov/cdash/test/3740451

It appears this is due to failing comparisons: 

```

======================================================================
FAIL: test_all (__main__.TestAdjointSolve)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nightlyCDash/build/IKTAlbanyFPECheckDbg/pyAlbany/tests/randCompress/adjointSolve.py", line 59, in test_all
    self.assertTrue(np.abs(eigVals - expected_eigVals) < tol)
AssertionError: array([False]) is not true

----------------------------------------------------------------------
Ran 1 test in 80.038s

FAILED (failures=1)
```

In the nightly spack build, I'm also seeing that PyAlbany_RSVDsinglePass fails.  Here is how the output looks like: 

```
114: resp<HessianVec>: 0.174878 [ -0.0178581 ] [ 0 [ 0 ] 0 [ 0 ] 0 [ 0 ] 0 [ 0 ] ]
114: resp<HessianVec>: 0 [ 0 ] [ 0 [ 0 ] 0 [ 0 ] 0 [ 0 ] 0 [ 0 ] ]
114: resp<HessianVec>: 0.174878 [ 0 ] [ 0 [ 0 ] 0 [ 0 ] 0 [ 0 ] 0 [ 0 ] ]
114: resp<HessianVec>: 0 [ 0 ] [ 0 [ 0 ] 0 [ 0 ] 0 [ 0 ] 0 [ 0 ] ]
114: F~PyProblem()
114: ~PyParallelEnv()
114:
114: ======================================================================
114: FAIL: test_all (__main__.TestSinglePass)
114: ----------------------------------------------------------------------
114: Traceback (most recent call last):
114:   File "/tmp/ikalash/spack-stage/spack-stage-albany-develop-4exxhfjns66haqdoww6kvu2mqi5dnm6h/spack-build-4exxhfj/pyAlbany/tests/randCompress/steadyHeatRSVDsinglePass.py", line 65, in test_all
114:     self.assertTrue(error <= errorBound)
114: AssertionError: False is not true
```

@kliegeois can you please have a look at this?

**Comment by kliegeois** [comment]
@ikalash I will look at it this week.

**Comment by ikalash** [comment]
This PR might have fixed it: https://github.com/trilinos/Trilinos/pull/12356#issuecomment-1745640880 .  Please stay tuned to see how the nightlies look tomorrow.
